{
 "title": "Domotica",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Oficina",
   "type": "stat",
   "gridPos": { "h": 6, "w": 2, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "domotica",
     "rawSql": "SELECT\n  CONVERT_TZ(ts, 'SYSTEM', '+00:00') AS \"time\",\n  JSON_VALUE(status_json, '$.dps.\"1\"') / 10 AS \"Temperatura\",\n  JSON_VALUE(status_json, '$.dps.\"2\"') /1 AS \"Humedad\"\nFROM device_status\nWHERE\n  device_name = 'termometro_oficina'\nORDER BY ts ASC"
    }
   ]
  },
  {
   "title": "Dormitorio",
   "type": "stat",
   "gridPos": { "h": 6, "w": 2, "x": 2, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "domotica",
     "rawSql": "SELECT\n  CONVERT_TZ(ts, 'SYSTEM', '+00:00') AS \"time\",\n  JSON_VALUE(status_json, '$.dps.\"1\"') / 10 AS \"Temperatura\",\n  JSON_VALUE(status_json, '$.dps.\"2\"') /1 AS \"Humedad\"\nFROM device_status\nWHERE\n  device_name = 'termometro_dormitorio'\nORDER BY ts ASC"
    }
   ]
  },
  {
   "title": "salon",
   "type": "stat",
   "gridPos": { "h": 6, "w": 2, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "domotica",
     "rawSql": "SELECT\n  CONVERT_TZ(ts, 'SYSTEM', '+00:00') AS \"time\",\n  JSON_VALUE(status_json, '$.dps.\"27\"') / 10 AS \"Temperatura\",\n  JSON_VALUE(status_json, '$.dps.\"46\"') / 1 AS \"Humedad\"\nFROM device_status\nWHERE\n  device_name = 'termometro_display_salon'\nORDER BY ts ASC"
    }
   ]
  },
  {
   "title": "Exterior",
   "type": "stat",
   "gridPos": { "h": 6, "w": 2, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "domotica",
     "rawSql": "SELECT\n  CONVERT_TZ(ts, 'SYSTEM', '+00:00') AS \"time\",\n  JSON_VALUE(status_json, '$.dps.\"1\"') / 10 AS \"Temperatura\",\n  JSON_VALUE(status_json, '$.dps.\"2\"') /1 AS \"Humedad\"\nFROM device_status\nWHERE\n  device_name = 'termometro_salon'\nORDER BY ts ASC"
    }
   ]
  },
  {
   "title": "Diferencia int -ext",
   "type": "stat",
   "gridPos": { "h": 6, "w": 2, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "domotica",
     "rawSql": "SELECT\n  (\n    (SELECT CAST(JSON_VALUE(status_json, '$.dps.\"1\"') AS DECIMAL(10,2))\n     FROM device_status \n     WHERE device_name = 'termometro_salon' \n     ORDER BY ts DESC LIMIT 1) \n    - \n    (SELECT CAST(JSON_VALUE(status_json, '$.dps.\"1\"') AS DECIMAL(10,2))\n     FROM device_status \n     WHERE device_name = 'termometro_dormitorio' \n     ORDER BY ts DESC LIMIT 1)\n  ) / 10 AS \"Diferencia Actual\""
    }
   ]
  },
  {
   "title": "Intensidad",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 3, "x": 10, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "amp" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "domotica",
     "rawSql": "SELECT\n  ts AS \"time\",\n  -- Bytes 6-8: Potencia (Dividido por 1000)\n  -- CONV(HEX(SUBSTR(decoded_blob, 6, 3)), 16, 10) / 1000 AS \"Potencia (KW)\",\n  -- Bytes 3-5: Potencia (Dividido por 1000)\n  CONV(HEX(SUBSTR(decoded_blob, 3, 3)), 16, 10) / 1000 AS \"Intensidad (A)\"\nFROM (\n  SELECT \n    ts,\n    -- Decodificamos el Base64 que está dentro del JSON en la clave \"6\" (o el número que corresponda en tu dps)\n    FROM_BASE64(JSON_VALUE(status_json, '$.dps.\"6\"')) AS decoded_blob\n  FROM device_status \n  WHERE \n    device_name = 'Automatico' \n    AND $__timeFilter(ts)\n) AS raw_data\nORDER BY ts ASC"
    }
   ]
  },
  {
   "title": "Potencia",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 3, "x": 13, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "kwatt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "domotica",
     "rawSql": "SELECT\n  CONVERT_TZ(ts, 'SYSTEM', '+00:00') AS \"time\",\n  -- Bytes 6-8: Potencia (Dividido por 1000)\n  CONV(HEX(SUBSTR(decoded_blob, 6, 3)), 16, 10) / 1000 AS \"Potencia (KW)\"\n\nFROM (\n  SELECT \n    ts,\n    -- Decodificamos el Base64 que está dentro del JSON en la clave \"6\" (o el número que corresponda en tu dps)\n    FROM_BASE64(JSON_VALUE(status_json, '$.dps.\"6\"')) AS decoded_blob\n  FROM device_status \n  WHERE \n    device_name = 'Automatico' \n    AND $__timeFilter(ts)\n) AS raw_data\nORDER BY ts ASC"
    }
   ]
  },
  {
   "title": "Tension",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "domotica",
     "rawSql": "SELECT\n  CONVERT_TZ(ts, 'SYSTEM', '+00:00') AS \"time\",\n  -- Bytes 6-8: Potencia (Dividido por 1000)\n  -- CONV(HEX(SUBSTR(decoded_blob, 6, 3)), 16, 10) / 1000 AS \"Potencia (KW)\",\n  -- Bytes 3-5: Potencia (Dividido por 1000)\n  -- CONV(HEX(SUBSTR(decoded_blob, 3, 3)), 16, 10) / 1000 AS \"Intensidad (A)\"\n  -- Bytes 1-2: Tensión (Dividido por 10)\n  CONV(HEX(SUBSTR(decoded_blob, 1, 2)), 16, 10) / 10 AS \"Tensión (V)\"\n\nFROM (\n  SELECT \n    ts,\n    -- Decodificamos el Base64 que está dentro del JSON en la clave \"6\" (o el número que corresponda en tu dps)\n    FROM_BASE64(JSON_VALUE(status_json, '$.dps.\"6\"')) AS decoded_blob\n  FROM device_status \n  WHERE \n    device_name = 'Automatico' \n    AND JSON_EXISTS(status_json, '$.dps.\"6\"') -- ESTO FILTRA SOLO LAS FILAS QUE TIENEN EL DPS 6\n    AND $__timeFilter(ts)\n) AS raw_data\nORDER BY ts ASC"
    }
   ]
  },
  {
   "title": "Calentando",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 19, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "domotica",
     "rawSql": "SELECT\n  CONVERT_TZ(ts, 'SYSTEM', '+00:00') AS \"time\",\n  CAST(JSON_VALUE(status_json, '$.heating.value') AS INT ) AS heating\nFROM device_status\nWHERE\n  device_name = 'termo' \n  AND $__timeFilter(ts)\nORDER BY ts ASC"
    }
   ]
  },
  {
   "title": "Temperatura termo",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 3, "x": 21, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "domotica",
     "rawSql": "SELECT\n  CONVERT_TZ(ts, 'SYSTEM', '+00:00') AS \"time\",\n  CAST(JSON_VALUE(status_json, '$.current_temperature.value') AS DOUBLE) AS \"Temperatura Termo\"\nFROM device_status\nWHERE\n  device_name = 'termo' \n  AND $__timeFilter(ts)\nORDER BY ts ASC"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 19, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "domotica",
     "rawSql": "SELECT\n  CONVERT_TZ(ts, 'SYSTEM', '+00:00') AS \"time\",\n  CAST(JSON_VALUE(status_json, '$.eco.value') AS INT ) AS \"Modo Eco\",\n  CAST(JSON_VALUE(status_json, '$.required_temperature.value') AS DOUBLE) AS \"Temperatura requerida\"\nFROM device_status\nWHERE\n  device_name = 'termo' \n  AND $__timeFilter(ts)\nORDER BY ts ASC"
    }
   ]
  },
  {
   "title": "Temperatura",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 20, "x": 0, "y": 6 },
   "targets": [
    {
     "dataset": "domotica",
     "rawSql": "SELECT\r\n  CONVERT_TZ(ts, 'SYSTEM', '+00:00') AS \"time\",\r\n  MAX(CASE WHEN device_name = 'termometro_salon' THEN CAST(JSON_VALUE(status_json, '$.dps.\"1\"') AS DECIMAL(10,2)) / 10 END) AS \"Exterior\",\r\n  MAX(CASE WHEN device_name = 'termometro_oficina' THEN CAST(JSON_VALUE(status_json, '$.dps.\"1\"') AS DECIMAL(10,2)) / 10 END) AS \"oficina\",\r\n  MAX(CASE WHEN device_name = 'termometro_dormitorio' THEN CAST(JSON_VALUE(status_json, '$.dps.\"1\"') AS DECIMAL(10,2)) / 10 END) AS \"Dormitorio\",\r\n  MAX(CASE WHEN device_name = 'termometro_display_salon' THEN CAST(JSON_VALUE(status_json, '$.dps.\"27\"') AS DECIMAL(10,2)) / 10 END) AS \"Salon\"\r\nFROM device_status\r\nWHERE\r\n  device_name IN ('termometro_salon', 'termometro_dormitorio','termometro_display_salon','termometro_oficina')\r\n  AND $__timeFilter(ts)\r\nGROUP BY 1\r\nORDER BY 1 ASC"
    }
   ]
  },
  {
   "title": "Puerta",
   "type": "table",
   "gridPos": { "h": 11, "w": 4, "x": 20, "y": 6 },
   "targets": [
    {
     "dataset": "domotica",
     "rawSql": "SELECT\n  CONVERT_TZ(ts, 'SYSTEM', '+00:00') AS \"time\",\n  JSON_VALUE(status_json, '$.dps.\"1\"') AS \"Estado\"\nFROM device_status\nWHERE\n  device_name = 'Puerta_entrada'\nORDER BY ts DESC LIMIT 6"
    }
   ]
  },
  {
   "title": "Potencia",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 20, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "kwatt" } },
   "targets": [
    {
     "dataset": "domotica",
     "rawSql": "SELECT\n  CONVERT_TZ(ts, 'SYSTEM', '+00:00') AS \"time\",\n  -- Bytes 6-8: Potencia (Dividido por 1000)\n  CONV(HEX(SUBSTR(decoded_blob, 6, 3)), 16, 10) / 1000 AS \"Potencia (KW)\"\nFROM (\n  SELECT \n    ts,\n    -- Decodificamos el Base64 que está dentro del JSON en la clave \"6\" (o el número que corresponda en tu dps)\n    FROM_BASE64(JSON_VALUE(status_json, '$.dps.\"6\"')) AS decoded_blob\n  FROM device_status \n  WHERE \n    device_name = 'Automatico' \n    AND JSON_EXISTS(status_json, '$.dps.\"6\"') -- ESTO FILTRA SOLO LAS FILAS QUE TIENEN EL DPS 6\n    AND $__timeFilter(ts)\n) AS raw_data\nORDER BY ts ASC"
    }
   ]
  },
  {
   "title": "Alertas Automatico",
   "type": "table",
   "gridPos": { "h": 13, "w": 4, "x": 20, "y": 17 },
   "targets": [
    {
     "dataset": "domotica",
     "rawSql": "SELECT\n  CONVERT_TZ(ts, 'SYSTEM', '+00:00') AS \"time\",\n  JSON_VALUE(status_json, '$.dps.\"9\"') AS \"fault\"\nFROM device_status\nWHERE\n  device_name = 'Automatico'\n  AND JSON_EXISTS(status_json, '$.dps.\"9\"') -- ESTO FILTRA SOLO LAS FILAS QUE TIENEN EL DPS 1\n  AND JSON_VALUE(status_json, '$.dps.\"9\"')\nORDER BY ts DESC LIMIT 10"
    }
   ]
  },
  {
   "title": "Temperatura termo",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 20, "x": 0, "y": 20 },
   "targets": [
    {
     "dataset": "domotica",
     "rawSql": "SELECT\n  CONVERT_TZ(ts, 'SYSTEM', '+00:00') AS \"time\",\n  CAST(JSON_VALUE(status_json, '$.current_temperature.value') AS DOUBLE) AS \"Temperatura Termo\"\nFROM device_status\nWHERE\n  device_name = 'termo' \n  AND $__timeFilter(ts)\nORDER BY ts ASC"
    }
   ]
  },
  {
   "title": "Humedad",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 20, "x": 0, "y": 26 },
   "targets": [
    {
     "dataset": "domotica",
     "rawSql": "SELECT\r\n  CONVERT_TZ(ts, 'SYSTEM', '+00:00') AS \"time\",\r\n  MAX(CASE WHEN device_name = 'termometro_salon' THEN CAST(JSON_VALUE(status_json, '$.dps.\"2\"') AS DECIMAL(10,2)) / 1 END) AS \"Exterior\",\r\n  MAX(CASE WHEN device_name = 'termometro_oficina' THEN CAST(JSON_VALUE(status_json, '$.dps.\"2\"') AS DECIMAL(10,2)) / 1 END) AS \"oficina\",\r\n  MAX(CASE WHEN device_name = 'termometro_dormitorio' THEN CAST(JSON_VALUE(status_json, '$.dps.\"2\"') AS DECIMAL(10,2)) / 1 END) AS \"Dormitorio\",\r\n  MAX(CASE WHEN device_name = 'termometro_display_salon' THEN CAST(JSON_VALUE(status_json, '$.dps.\"46\"') AS DECIMAL(10,2)) / 1 END) AS \"Salon\"\r\nFROM device_status\r\nWHERE\r\n  device_name IN ('termometro_salon', 'termometro_dormitorio','termometro_display_salon','termometro_oficina')\r\n  AND $__timeFilter(ts)\r\nGROUP BY 1\r\nORDER BY 1 ASC"
    }
   ]
  },
  {
   "title": "oficina",
   "type": "bargauge",
   "gridPos": { "h": 9, "w": 1, "x": 20, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "domotica",
     "rawSql": "SELECT\n  CONVERT_TZ(ts, 'SYSTEM', '+00:00') AS \"time\",\n  JSON_VALUE(status_json, '$.dps.\"4\"') /1 AS \"Batt\"\nFROM device_status\nWHERE\n  device_name = 'termometro_oficina'\nORDER BY ts ASC"
    }
   ]
  },
  {
   "title": "Exterior",
   "type": "bargauge",
   "gridPos": { "h": 9, "w": 1, "x": 21, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "domotica",
     "rawSql": "SELECT\n  CONVERT_TZ(ts, 'SYSTEM', '+00:00') AS \"time\",\n  JSON_VALUE(status_json, '$.dps.\"4\"') /1 AS \"Batt\"\nFROM device_status\nWHERE\n  device_name = 'termometro_salon'\nORDER BY ts ASC"
    }
   ]
  },
  {
   "title": "Dormi",
   "type": "bargauge",
   "gridPos": { "h": 9, "w": 1, "x": 22, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "domotica",
     "rawSql": "SELECT\n  CONVERT_TZ(ts, 'SYSTEM', '+00:00') AS \"time\",\n  JSON_VALUE(status_json, '$.dps.\"4\"') /1 AS \"Batt\"\nFROM device_status\nWHERE\n  device_name = 'termometro_dormitorio'\nORDER BY ts ASC"
    }
   ]
  },
  {
   "title": "batt display salon",
   "type": "logs",
   "gridPos": { "h": 9, "w": 1, "x": 23, "y": 30 },
   "targets": [
    {
     "dataset": "domotica",
     "rawSql": "SELECT\n  CONVERT_TZ(ts, 'SYSTEM', '+00:00') AS \"time\",\n  JSON_VALUE(status_json, '$.dps.\"101\"') AS \"Batt\"\nFROM device_status\nWHERE\n  device_name = 'termometro_display_salon'\n  AND $__timeFilter(ts)\nORDER BY ts ASC LIMIT 1"
    }
   ]
  },
  {
   "title": "calentador termo",
   "type": "state-timeline",
   "gridPos": { "h": 2, "w": 20, "x": 0, "y": 33 },
   "targets": [
    {
     "dataset": "domotica",
     "rawSql": "SELECT\n  CONVERT_TZ(ts, 'SYSTEM', '+00:00') AS \"time\",\n  CAST(JSON_VALUE(status_json, '$.heating.value') AS INT ) AS heating\nFROM device_status\nWHERE\n  device_name = 'termo' \n  AND $__timeFilter(ts)\nORDER BY ts ASC"
    }
   ]
  },
  {
   "title": "ECO termo",
   "type": "state-timeline",
   "gridPos": { "h": 2, "w": 20, "x": 0, "y": 35 },
   "targets": [
    {
     "dataset": "domotica",
     "rawSql": "SELECT\n  CONVERT_TZ(ts, 'SYSTEM', '+00:00') AS \"time\",\n  CAST(JSON_VALUE(status_json, '$.eco.value') AS INT ) AS eco\nFROM device_status\nWHERE\n  device_name = 'termo' \n  AND $__timeFilter(ts)\nORDER BY ts ASC"
    }
   ]
  },
  {
   "title": "Termometro Exterior",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 10, "x": 0, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "dataset": "domotica",
     "rawSql": "SELECT\n  CONVERT_TZ(ts, 'SYSTEM', '+00:00') AS \"time\",\n  JSON_VALUE(status_json, '$.dps.\"1\"') / 10 AS \"Temperatura\"\nFROM device_status\nWHERE\n  device_name = 'termometro_salon'\n  AND $__timeFilter(ts)\nORDER BY ts ASC"
    }
   ]
  },
  {
   "title": "Termometro Oficina",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 10, "x": 10, "y": 37 },
   "targets": [
    {
     "dataset": "domotica",
     "rawSql": "SELECT\n  CONVERT_TZ(ts, 'SYSTEM', '+00:00') AS \"time\",\n  JSON_VALUE(status_json, '$.dps.\"1\"') / 10 AS \"Temperatura\"\nFROM device_status\nWHERE\n  device_name = 'termometro_oficina'\n  AND $__timeFilter(ts)\nORDER BY ts ASC"
    }
   ]
  },
  {
   "title": "Tension",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 4, "x": 20, "y": 39 },
   "targets": [
    {
     "dataset": "domotica",
     "rawSql": "SELECT\n  CONVERT_TZ(ts, 'SYSTEM', '+00:00') AS \"time\",\n  -- Bytes 6-8: Potencia (Dividido por 1000)\n  -- CONV(HEX(SUBSTR(decoded_blob, 6, 3)), 16, 10) / 1000 AS \"Potencia (KW)\",\n  -- Bytes 3-5: Potencia (Dividido por 1000)\n  -- CONV(HEX(SUBSTR(decoded_blob, 3, 3)), 16, 10) / 1000 AS \"Intensidad (A)\"\n  -- Bytes 1-2: Tensión (Dividido por 10)\n  CONV(HEX(SUBSTR(decoded_blob, 1, 2)), 16, 10) / 10 AS \"Tensión (V)\"\n\nFROM (\n  SELECT \n    ts,\n    -- Decodificamos el Base64 que está dentro del JSON en la clave \"6\" (o el número que corresponda en tu dps)\n    FROM_BASE64(JSON_VALUE(status_json, '$.dps.\"6\"')) AS decoded_blob\n  FROM device_status \n  WHERE \n    device_name = 'Automatico' \n    AND $__timeFilter(ts)\n) AS raw_data\nORDER BY ts ASC"
    }
   ]
  },
  {
   "title": "Termometro display salon",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 10, "x": 0, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "dataset": "domotica",
     "rawSql": "SELECT\n  CONVERT_TZ(ts, 'SYSTEM', '+00:00') AS \"time\",\n  JSON_VALUE(status_json, '$.dps.\"27\"') / 10 AS \"Temperatura\"\nFROM device_status\nWHERE\n  device_name = 'termometro_display_salon'\n  AND $__timeFilter(ts)\nORDER BY ts ASC"
    }
   ]
  },
  {
   "title": "Termometro dormitorio",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 10, "x": 10, "y": 42 },
   "targets": [
    {
     "dataset": "domotica",
     "rawSql": "SELECT\n  CONVERT_TZ(ts, 'SYSTEM', '+00:00') AS \"time\",\n  JSON_VALUE(status_json, '$.dps.\"1\"') / 10 AS \"Temperatura\"\nFROM device_status\nWHERE\n  device_name = 'termometro_dormitorio'\n  AND $__timeFilter(ts)\nORDER BY ts ASC"
    }
   ]
  },
  {
   "title": "Radiador Salon",
   "type": "state-timeline",
   "gridPos": { "h": 4, "w": 20, "x": 0, "y": 47 },
   "targets": [
    {
     "dataset": "domotica",
     "rawSql": "SELECT\n  CONVERT_TZ(ts, 'SYSTEM', '+00:00') AS \"time\",\n  JSON_VALUE(status_json, '$.dps.\"1\"') * 1600 AS \"state\",\n  JSON_VALUE(status_json, '$.dps.\"22\"') / 10 AS \"Potencia\"\nFROM device_status\nWHERE\n  device_name = 'radiador_salon'\n  AND $__timeFilter(ts)\nORDER BY ts ASC"
    }
   ]
  },
  {
   "title": "Radiador Dormitorio",
   "type": "state-timeline",
   "gridPos": { "h": 4, "w": 20, "x": 0, "y": 51 },
   "targets": [
    {
     "dataset": "domotica",
     "rawSql": "SELECT\n  CONVERT_TZ(ts, 'SYSTEM', '+00:00') AS \"time\",\n  JSON_VALUE(status_json, '$.dps.\"1\"') * 1200 AS \"state\",\n  JSON_VALUE(status_json, '$.dps.\"22\"') / 10 AS \"Potencia\"\nFROM device_status\nWHERE\n  device_name = 'radiador_dormitorio'\n  AND $__timeFilter(ts)\nORDER BY ts ASC"
    }
   ]
  },
  {
   "title": "Radiador oficina",
   "type": "state-timeline",
   "gridPos": { "h": 4, "w": 20, "x": 0, "y": 55 },
   "targets": [
    {
     "dataset": "domotica",
     "rawSql": "SELECT\n  CONVERT_TZ(ts, 'SYSTEM', '+00:00') AS \"time\",\n  JSON_VALUE(status_json, '$.dps.\"1\"') * 600 AS \"state\",\n  JSON_VALUE(status_json, '$.dps.\"22\"') / 10 AS \"Potencia\"\nFROM device_status\nWHERE\n  device_name = 'radiador_oficina'\n  AND $__timeFilter(ts)\nORDER BY ts ASC"
    }
   ]
  },
  {
   "title": "Intensidad",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 20, "x": 0, "y": 59 },
   "fieldConfig": { "defaults": { "unit": "amp" } },
   "targets": [
    {
     "dataset": "domotica",
     "rawSql": "SELECT\n  CONVERT_TZ(ts, 'SYSTEM', '+00:00') AS \"time\",\n  CAST(CONV(HEX(SUBSTR(decoded_blob, 3, 3)), 16, 10) / 1000 AS DOUBLE) AS \"Intensidad (A)\"\nFROM (\n  SELECT \n    ts,\n    FROM_BASE64(JSON_VALUE(status_json, '$.dps.\"6\"')) AS decoded_blob\n  FROM device_status \n  WHERE \n    device_name = 'Automatico' \n    AND JSON_EXISTS(status_json, '$.dps.\"6\"') -- ESTO FILTRA SOLO LAS FILAS QUE TIENEN EL DPS 6\n    AND $__timeFilter(ts)\n) AS raw_data\nORDER BY ts ASC"
    }
   ]
  },
  {
   "title": "humedad dormitorio",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 67 },
   "targets": [
    {
     "dataset": "domotica",
     "rawSql": "SELECT\n  CONVERT_TZ(ts, 'SYSTEM', '+00:00') AS \"time\",\n  JSON_VALUE(status_json, '$.dps.\"2\"') / 1 AS \"Humedad\"\nFROM device_status\nWHERE\n  device_name = 'termometro_dormitorio'\n  AND $__timeFilter(ts)\nORDER BY ts ASC"
    }
   ]
  },
  {
   "title": "humedad exterior",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 67 },
   "targets": [
    {
     "dataset": "domotica",
     "rawSql": "SELECT\n  CONVERT_TZ(ts, 'SYSTEM', '+00:00') AS \"time\",\n  JSON_VALUE(status_json, '$.dps.\"2\"') / 1 AS \"Humedad\"\nFROM device_status\nWHERE\n  device_name = 'termometro_salon'\n  AND $__timeFilter(ts)\nORDER BY ts ASC"
    }
   ]
  },
  {
   "title": "Humedad Oficina",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 76 },
   "targets": [
    {
     "dataset": "domotica",
     "rawSql": "SELECT\n  CONVERT_TZ(ts, 'SYSTEM', '+00:00') AS \"time\",\n  JSON_VALUE(status_json, '$.dps.\"2\"') / 1 AS \"Humedad\"\nFROM device_status\nWHERE\n  device_name = 'termometro_oficina'\n  AND $__timeFilter(ts)\nORDER BY ts ASC"
    }
   ]
  },
  {
   "title": "Humedad display salon",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 76 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "dataset": "domotica",
     "rawSql": "SELECT\n  CONVERT_TZ(ts, 'SYSTEM', '+00:00') AS \"time\",\n  JSON_VALUE(status_json, '$.dps.\"46\"') /1 AS \"Humedad\"\nFROM device_status\nWHERE\n  device_name = 'termometro_display_salon'\n  AND $__timeFilter(ts)\nORDER BY ts ASC"
    }
   ]
  },
  {
   "title": "Poencia consumida por dia",
   "type": "barchart",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 85 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "targets": [
    {
     "dataset": "domotica",
     "rawSql": "SELECT\n  $__timeGroup(ts, '24h') AS \"time\",\n  (MAX(CAST(JSON_VALUE(status_json, '$.dps.\"1\"') AS DECIMAL(10,2))) - MIN(CAST(JSON_VALUE(status_json, '$.dps.\"1\"') AS DECIMAL(10,2)))) / 100 AS \"kWh Diario\"\nFROM device_status\nWHERE\n  device_name = 'Automatico'\n  AND $__timeFilter(ts)\nGROUP BY 1\nORDER BY 1 ASC"
    }
   ]
  }
 ]
}