apiVersion: v1
kind: Secret
metadata:
  name: mariadb-secret
  namespace: domotica
  labels:
    app.kubernetes.io/part-of: domotica
type: Opaque
stringData:
  MYSQL_ROOT_PASSWORD: root
  MYSQL_DATABASE: domotica
  MYSQL_USER: domotica
  MYSQL_PASSWORD: domotica_password
---
apiVersion: v1
kind: Secret
metadata:
  name: grafana-secret
  namespace: domotica
  labels:
    app.kubernetes.io/part-of: domotica
type: Opaque
stringData:
  GF_SECURITY_ADMIN_PASSWORD: admin
