apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mariadb-data
  namespace: domotica
  labels:
    app.kubernetes.io/part-of: domotica
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: grafana-data
  namespace: domotica
  labels:
    app.kubernetes.io/part-of: domotica
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi

